services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
